version: "3.8"
services:
  juno:
    build:
      context: .
      args:
        UPSTREAM_VERSION: v0.15.0-rc.4
    image: juno.public.dappnode.eth:2.0.0
    security_opt:
      - seccomp:unconfined
    ports:
      - "6060:6060"
      - "6061:6061"
    environment:
      ETH_L1_RPC_URL: http://execution.mainnet.staker.dappnode:8545
      NETWORK: "mainnet"
      EXTRA_OPTS: ""
      ENABLE_WS: "true"
      WS_PORT: "6061"
      WS_HOST: "0.0.0.0"
    volumes:
      - juno_data:/var/lib/juno
    restart: unless-stopped

volumes:
  juno_data: {}
